name: cross_fitness
description: "A new Flutter project."
publish_to: 'none'
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  flutter_bloc: ^7.1.0
  firebase_storage: ^11.6.5
  dots_indicator: ^3.0.0
  percent_indicator: ^4.2.3
  url_launcher: ^6.2.4
  sliding_up_panel: ^2.0.0+1
  video_player: ^2.8.2
  # chewie:
  #   git:
  #     url: git@github.com:v1nnk1/chewie.git
  custom_timer: ^0.2.3
  image_picker: ^1.0.7
  flutter_local_notifications: ^16.3.2
  #The following dependencies do not satisfy the required version:
  # project ':flutter_native_timezone' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
  # flutter_native_timezone: ^2.0.0
  flutter_timezone: ^1.0.8
  permission_handler: ^11.3.0
  chewie: ^1.7.5
  flutter_secure_storage: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/home/
    - assets/images/onboarding/
    - assets/images/exercises/
    - assets/images/auth/
    - assets/icons/home/
    - assets/icons/workouts/
    - assets/icons/social_networks/
    - assets/videos/workouts/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
