// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCcFjg4OnbB7MVAPB5iFctMGjr6dkQebw',
    appId: '1:755666712168:web:d39dc15fd778d1fb652ddd',
    messagingSenderId: '755666712168',
    projectId: 'cross-fitness-f4c86',
    authDomain: 'cross-fitness-f4c86.firebaseapp.com',
    storageBucket: 'cross-fitness-f4c86.appspot.com',
    measurementId: 'G-W00NS06L69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj1ukCetyIAQ-UJI7IBaAmQlnPhYjUB-s',
    appId: '1:755666712168:android:30637decdcac3b37652ddd',
    messagingSenderId: '755666712168',
    projectId: 'cross-fitness-f4c86',
    storageBucket: 'cross-fitness-f4c86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADh56JpzFsb_c-5xXHpBn0dYkMCYqhAyY',
    appId: '1:755666712168:ios:d1b5d127465e8e4d652ddd',
    messagingSenderId: '755666712168',
    projectId: 'cross-fitness-f4c86',
    storageBucket: 'cross-fitness-f4c86.appspot.com',
    iosBundleId: 'com.example.crossFitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADh56JpzFsb_c-5xXHpBn0dYkMCYqhAyY',
    appId: '1:755666712168:ios:db7b52f5c5342bd0652ddd',
    messagingSenderId: '755666712168',
    projectId: 'cross-fitness-f4c86',
    storageBucket: 'cross-fitness-f4c86.appspot.com',
    iosBundleId: 'com.example.crossFitness.RunnerTests',
  );
}
